"""add_index_user_created

Revision ID: 70b0a55f308c
Revises: f84d00e39a86
Create Date: 2026-06-12 02:41:22.461047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b0a55f308c'
down_revision: Union[str, Sequence[str], None] = 'f84d00e39a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_diary_entries_user_created', 'diary_entries', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_diary_entries_user_created', table_name='diary_entries')
    # ### end Alembic commands ###
