"""add_language_code

Revision ID: d033045c90ce
Revises: fa819d3cb62f
Create Date: 2026-07-01 17:18:57.202799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd033045c90ce'
down_revision: Union[str, Sequence[str], None] = 'fa819d3cb62f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language_code', sa.String(length=5), nullable=True))
    op.execute("UPDATE users SET language_code = 'ru' WHERE language_code IS NULL")
    op.alter_column('users', 'language_code', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language_code')
    # ### end Alembic commands ###
