"""add_conversation_log

Revision ID: f84d00e39a86
Revises: 775711e58271
Create Date: 2026-06-12 01:15:12.738476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f84d00e39a86'
down_revision: Union[str, Sequence[str], None] = '775711e58271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary_entries', sa.Column('conversation_log', sa.Text(), nullable=True))
    op.execute("UPDATE diary_entries SET conversation_log = user_text")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary_entries', 'conversation_log')
    # ### end Alembic commands ###
