"""add cached_insights to users

Revision ID: fa819d3cb62f
Revises: 814ee495c872
Create Date: 2026-06-27 02:12:02.879130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa819d3cb62f'
down_revision: Union[str, Sequence[str], None] = '814ee495c872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cached_insights', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('insights_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'insights_updated_at')
    op.drop_column('users', 'cached_insights')
    # ### end Alembic commands ###
